language: python
python:
- '2.7'
sudo: required
services:
- docker
install:
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
script:
- kb-sdk test
after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/kb_tophat2 /kb/module/lib/
- coverage report -m
- coveralls
env:
  global:
    secure: H6s96Gcx/y+gXCtbrGKKkj81geHc3sOYrQYCMy8eTnHTTd+c3OJlvNN3tHEb0Yy+cZrXFfFam/+ZHY5DAjK/V/LUH5DwgFeP0MDHMd7gp/0pJ9FQVkvwu8tx8Z85HAdOzV78aF7fKyTe+eH2DjNiRGO3Cv7bV3+dGPYG8qsyQVXXEse1tSIOph9Ykjh21Sv29JifO4W9QswbWea+2ZzvnwY9iUxxJgwaJh15P2CAPMHZRyWaJLvcA8Aj4n4rbD1BD+tXY7K2lXm2x/pxbMSn0yLCDEQfqG1Pc6TfCWVyVOkugvaVhKtofSyACRdlVieP9iPhWFl3xiookjLE4cQsVW/3t9WrjccHIcCF4V0vpBn5r78aeTH9Aa+TPksrt8ovcvtYSBFyokbhRf6WfCzl7m83DmwLe0JTRXQ5AXfUQG3uxJbuPpdXht1J52rZEpaS6TWiwspa74lUrOK8B0Bw4p1EDViojQS6JQ785jFcTHz/KcmujRLTiLvt78K/yPU6b0yI/aa8V+4Nq6M6gHbIvIItvXRgaTweDajbFplOWH3zOuJS8bshEXYekv7idw0zqogDGyjLusV5pJxt/YIdt9aJNjHuhrI20DURJH3KbIot/LWCDLZa7tODdOX6kscyIRLDD8di05Srb1dVQe+KaJIbWDpZ+EspFSp8HKNV0E8=
